/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BatchRegistry__factory } from "./BatchRegistry__factory";
export { RecallManager__factory } from "./RecallManager__factory";
